### ISSUE TITLE
Requests and issues

### ISSUE THREAD

**Issue by gameboy9** [MrStarbird/PStar4-Randomizer#1]
Here's a conversation with current issues and feature requests for this randomizer:

- If it's optional to the players, I'm a fan of randomizing equipment stats.  Does randomizing enemy stats include randomizing enemy moves?  (Meaning that an infant worm, for example, could cast Megido?)
(in which case we all LOL and say... "well then!") :smiley:

kaiten619 - Today at 7:02 AM
the only thing i hope it gets randomized is stat growth
cuz i love having new stat growth in each rando. cuz it feels like we can use underrated characters
also i want skill randomized for each member except for the androids(since they have to get theirs in chests)

gameboyf9 - Today at 7:06 AM
- One thing I would look into is instant text so you can take care of cut scenes significantly faster.
- The other issue I have is that your randomizer only accepts SMC files.  My ROM was a GEN file... now when I renamed it to an SMC file, the randomizer worked successfully, so I think you should allow GEN files under the same ROM checks.

**Comment by MrStarbird** [comment]
All great ideas. I will keep this up for reference. Thank you! :D

**Comment by SenseiLeRoof** [comment]
Install location should be user-selectable.

**Comment by MrStarbird** [comment]
Yes, I agree. I will try to see what I can do. Not sure why the installer won't do it, but it's worth learning. Thanks for the suggestion!

**Comment by SenseiLeRoof** [comment]
If it helps, here's where it winds up getting stuck on my system:

C:\Users\\(obscured, just in case)\AppData\Local\Apps\2.0\829H87NP.WJC\L9TML08Y.XBE\phan..tion_b29cce82bcf27b74_0001.0000_9bbd77d8e06963c8

**Comment by rdb1200** [comment]
hi mr starbird wanted too try this out but am getting this error 

System.UnauthorizedAccessException: Access to the path 'C:\roms\pstar4.smd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at PStarIV_Randomizer.Form1.btnRandomize_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Windows 10 and i have delete my temp files etc just wont let me open it

**Comment by rdb1200** [comment]
it seems i have found the problem its randomizer cant work with smd files bin file worked instant

**Comment by Noahb20** [comment]
Newbie here, where can i get a rom that will work with the randomizer? The one I have does not work.
